const TRD_CONFIG = Object.freeze({
  timeZone: 'America/Toronto',
  menuName: 'Tammy Roundtable Demo',
  demoFolderName: 'Tammy Roundtable Demo',
  calendarName: 'Tammy Roundtable Demo Calendar',
  formTitle: 'New Transaction Intake Demo',
  formDescription:
    'Demo-only form for the Tammy May 21 roundtable. Use sample data only. No live client or FINTRAC documents.',
  statuses: Object.freeze({
    extractionRequired: 'Extraction Required',
    sourceMissing: 'Source Missing',
    sourceChanged: 'Source Changed',
    runningExtraction: 'Running Extraction',
    extracted: 'Extracted',
    readyForReview: 'Ready For Review',
    reviewRejected: 'Review Rejected',
    runningDraft: 'Running Draft',
    draftFailed: 'Draft Failed',
    draftGenerated: 'Draft Generated',
  }),
  phases: Object.freeze({
    setup: 'Setup',
    seed: 'Seed',
    source: 'Source',
    extraction: 'Extraction',
    review: 'Review',
    draft: 'Draft',
  }),
  sheetNames: Object.freeze({
    intake: 'TransactionIntake',
    referenceData: 'ReferenceData',
    requiredDocs: 'RequiredDocs',
    tradeRecord: 'TradeRecord',
    dashboard: 'Dashboard',
    actionLog: 'ActionLog',
  }),
  propertyKeys: Object.freeze({
    demoFolderId: 'TRD_DEMO_FOLDER_ID',
    formId: 'TRD_FORM_ID',
    calendarId: 'TRD_CALENDAR_ID',
    claudeApiKey: 'TRD_CLAUDE_API_KEY',
    claudeApiUrl: 'TRD_CLAUDE_API_URL',
    claudeApiVersion: 'TRD_CLAUDE_API_VERSION',
    claudeModel: 'TRD_CLAUDE_MODEL',
    claudeExtractionModel: 'TRD_CLAUDE_EXTRACTION_MODEL',
    claudeDraftModel: 'TRD_CLAUDE_DRAFT_MODEL',
  }),
  defaultClaudeConfig: Object.freeze({
    apiUrl: 'https://api.anthropic.com/v1/messages',
    apiVersion: '2023-06-01',
    model: 'claude-sonnet-4-6',
    extractionMaxTokens: 2200,
    draftMaxTokens: 1600,
  }),
  formFields: Object.freeze([
    { key: 'transactionId', title: 'Transaction ID', type: 'text', required: true },
    { key: 'dealAddress', title: 'Property / Deal Address', type: 'text', required: true },
    { key: 'seller1', title: 'Seller 1', type: 'text', required: true },
    { key: 'buyer1', title: 'Buyer 1', type: 'text', required: true },
    { key: 'soldPrice', title: 'Sold Price', type: 'text', required: true },
    { key: 'saleDate', title: 'Sale Date', type: 'date', required: true },
    { key: 'possessionDate', title: 'Possession Date', type: 'date', required: true },
    { key: 'mlsNumber', title: 'MLS Number', type: 'text', required: true },
    { key: 'contractNumber', title: 'Contract Number', type: 'text', required: true },
    { key: 'condition1Name', title: 'Condition 1 Name', type: 'text', required: false },
    { key: 'condition1Date', title: 'Condition 1 Date', type: 'date', required: false },
    { key: 'condition2Name', title: 'Condition 2 Name', type: 'text', required: false },
    { key: 'condition2Date', title: 'Condition 2 Date', type: 'date', required: false },
    { key: 'listingRealtor', title: 'Listing Realtor', type: 'text', required: true },
    { key: 'sellingRealtor', title: 'Selling Realtor', type: 'text', required: true },
    { key: 'sellerLawyer', title: 'Seller Lawyer', type: 'text', required: true },
    { key: 'buyerLawyer', title: 'Buyer Lawyer', type: 'text', required: true },
    { key: 'clientEmail', title: 'Client Email', type: 'text', required: true },
    { key: 'operatorNotes', title: 'Operator Notes', type: 'paragraph', required: false },
  ]),
  intakeInternalColumns: Object.freeze([
    'Processing Status',
    'Source File Link',
    'Source File Id',
    'Source File Name',
    'Source File Mime Type',
    'Source File Modified At',
    'Package Folder Id',
    'Package Folder Link',
    'Condition Event Id',
    'Possession Event Id',
    'Current Attempt Id',
    'Current Attempt Number',
    'Extraction Timestamp',
    'Extraction Model Label',
    'Extraction Summary',
    'Extraction Pass/Fail',
    'Missing Field Summary',
    'Review Approved At',
    'Derived Notes Phase Cue',
    'Gmail Draft Link',
    'Gmail Draft Id',
    'Draft Model Label',
    'Trade Record Row',
    'Last Run At',
    'Last Result',
    'Last Error',
  ]),
  extractedFieldColumns: Object.freeze([
    { key: 'transactionId', header: 'Extracted Transaction ID' },
    { key: 'dealAddress', header: 'Extracted Deal Address' },
    { key: 'buyerName', header: 'Extracted Buyer' },
    { key: 'sellerName', header: 'Extracted Seller' },
    { key: 'soldPrice', header: 'Extracted Sold Price' },
    { key: 'saleDate', header: 'Extracted Sale Date' },
    { key: 'possessionDate', header: 'Extracted Possession Date' },
    { key: 'listingRealtor', header: 'Extracted Listing Realtor' },
    { key: 'sellingRealtor', header: 'Extracted Selling Realtor' },
    { key: 'condition1Name', header: 'Extracted Condition 1 Name' },
    { key: 'condition1Date', header: 'Extracted Condition 1 Date' },
    { key: 'condition2Name', header: 'Extracted Condition 2 Name' },
    { key: 'condition2Date', header: 'Extracted Condition 2 Date' },
    { key: 'buyerLawyer', header: 'Extracted Buyer Lawyer' },
    { key: 'sellerLawyer', header: 'Extracted Seller Lawyer' },
    { key: 'mlsNumber', header: 'Extracted MLS Number' },
    { key: 'contractNumber', header: 'Extracted Contract Number' },
  ]),
  extractionMinimumFieldKeys: Object.freeze([
    'dealAddress',
    'buyerName',
    'sellerName',
  ]),
  supportedSourceMimeTypes: Object.freeze({
    pdf: 'application/pdf',
    jpeg: 'image/jpeg',
    png: 'image/png',
    googleDoc: 'application/vnd.google-apps.document',
    docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    plainText: 'text/plain',
  }),
  referenceRows: Object.freeze([
    ['brokerageName', 'MaxWell Canyon Creek', 'Fixed demo brokerage name'],
    ['depositHolderText', 'Deposits held by MaxWell Canyon Creek trust', 'Fixed demo deposit-holder wording'],
    ['listingCommissionText', 'Sample listing commission wording kept fixed for this demo.', 'Trimmed commission text'],
    ['sellingCommissionText', 'Sample selling commission wording kept fixed for this demo.', 'Trimmed commission text'],
    ['tradeRecordDisclaimer', 'Demo-only trade record generated from selected source material and sample-safe defaults.', 'Shown in the trade-record preview'],
    ['nextStepEmailLabel', 'Review Draft', 'Used in the Gmail draft label'],
  ]),
  requiredDocs: Object.freeze([
    { category: 'Accepted Offer', name: 'Accepted OTP / Offer to Purchase' },
    { category: 'Deposit', name: 'Deposit Cheque / Proof of Deposit' },
    { category: 'Compliance', name: 'Area Forms / Consumer Agreement' },
    { category: 'Compliance', name: 'MLS Copy' },
    { category: 'Lawyers', name: 'Seller Lawyer Contact' },
    { category: 'Lawyers', name: 'Buyer Lawyer Contact' },
    { category: 'Conditions', name: 'Condition Waiver / Fulfillment' },
    { category: 'Closing', name: 'Transaction Report / Trade Record Review' },
  ]),
  dashboardAssetHeaders: Object.freeze(['Asset', 'Status', 'Link / Id', 'Notes']),
  dashboardTableHeaders: Object.freeze([
    'Transaction ID',
    'Status',
    'Source',
    'Attempt',
    'Review Approval',
    'Drive Folder',
    'Calendar',
    'Draft',
    'Trade Record',
    'Last Result',
  ]),
  requiredDocsHeaders: Object.freeze([
    'Transaction ID',
    'Document Category',
    'Document Name',
    'Status',
    'Notes',
    'Last Updated',
  ]),
  actionLogHeaders: Object.freeze([
    'Timestamp',
    'Transaction ID',
    'Attempt ID',
    'Attempt Number',
    'Phase',
    'Row Status',
    'Source File ID',
    'Source File Link',
    'Output Reference',
    'Result Summary',
    'Error Text',
  ]),
  tradeRecordHeaders: Object.freeze([
    'Transaction ID',
    'Attempt Number',
    'Attempt ID',
    'Source File',
    'Buyer',
    'Seller',
    'Deal Address',
    'Sold Price',
    'Sale Date',
    'Possession Date',
    'Listing Realtor',
    'Selling Realtor',
    'Condition 1',
    'Condition 2',
    'Seller Lawyer',
    'Buyer Lawyer',
    'MLS Number',
    'Contract Number',
    'Package Folder Link',
    'Draft Link',
    'Extraction Summary',
  ]),
  tradeRecordPreviewRows: Object.freeze([
    ['Transaction ID', 'transactionId'],
    ['Buyer', 'buyerName'],
    ['Seller', 'sellerName'],
    ['Deal Address', 'dealAddress'],
    ['Sold Price', 'soldPrice'],
    ['Sale Date', 'saleDate'],
    ['Possession Date', 'possessionDate'],
    ['Listing Realtor', 'listingRealtor'],
    ['Selling Realtor', 'sellingRealtor'],
    ['Condition 1', 'condition1'],
    ['Seller Lawyer', 'sellerLawyer'],
    ['Buyer Lawyer', 'buyerLawyer'],
    ['Source File', 'sourceFileLabel'],
    ['Extraction Summary', 'extractionSummary'],
  ]),
  folderTemplatePaths: Object.freeze([
    'Initial Prospect Folder',
    'Full Info Prospects Folder',
    'Full Info Prospects Folder/Financials',
    'Full Info Prospects Folder/Monthly Sales',
    'Full Info Prospects Folder/Franchise & Lease Agreements',
    'Full Info Prospects Folder/Payroll & Staff',
    'Full Info Prospects Folder/Incorporated Docs',
    'Full Info Prospects Folder/Store Photos',
    'Full Info Prospects Folder/Normalized Financials_',
  ]),
  sampleDocStatusPresets: Object.freeze({
    completed: Object.freeze({
      'Accepted OTP / Offer to Purchase': 'Received',
      'Deposit Cheque / Proof of Deposit': 'Received',
      'Area Forms / Consumer Agreement': 'Received',
      'MLS Copy': 'Received',
      'Seller Lawyer Contact': 'Received',
      'Buyer Lawyer Contact': 'Received',
      'Condition Waiver / Fulfillment': 'Missing',
      'Transaction Report / Trade Record Review': 'Expected',
    }),
    live: Object.freeze({
      'Accepted OTP / Offer to Purchase': 'Expected',
      'Deposit Cheque / Proof of Deposit': 'Expected',
      'Area Forms / Consumer Agreement': 'Received',
      'MLS Copy': 'Received',
      'Seller Lawyer Contact': 'Expected',
      'Buyer Lawyer Contact': 'Expected',
      'Condition Waiver / Fulfillment': 'Missing',
      'Transaction Report / Trade Record Review': 'Expected',
    }),
  }),
  sampleTransactions: Object.freeze({
    completed: Object.freeze({
      transactionId: 'RT-COMP-1001',
      dealAddress: '1128 4 Street SW, Calgary, AB',
      seller1: 'Maple Retail Holdings Ltd.',
      buyer1: 'Jordan Patel',
      soldPrice: '$425,000',
      saleDate: '2026-05-19',
      possessionDate: '2026-06-15',
      mlsNumber: 'A2145678',
      contractNumber: 'MCC-TR-1001',
      condition1Name: 'Financing',
      condition1Date: '2026-05-21',
      condition2Name: 'Landlord Consent',
      condition2Date: '2026-05-23',
      listingRealtor: 'Tammy MacDonald',
      sellingRealtor: 'Ava Singh',
      sellerLawyer: 'Jordan & Co. Law | 403-555-0112',
      buyerLawyer: 'Summit Legal | 403-555-0189',
      clientEmail: 'jordan.patel@example.com',
      operatorNotes:
        'Seeded fallback sample. Review draft only. Missing condition waiver left visible on purpose.',
      sampleProfile: 'completed',
    }),
    live: Object.freeze({
      transactionId: 'RT-LIVE-1002',
      dealAddress: '810 Centre Street N, Calgary, AB',
      seller1: 'Prairie Hospitality Group',
      buyer1: 'Carter Nguyen',
      soldPrice: '$612,000',
      saleDate: '2026-05-21',
      possessionDate: '2026-06-30',
      mlsNumber: 'A2148901',
      contractNumber: 'MCC-TR-1002',
      condition1Name: 'Due Diligence',
      condition1Date: '2026-05-24',
      condition2Name: 'Assignment Approval',
      condition2Date: '2026-05-26',
      listingRealtor: 'Tammy MacDonald',
      sellingRealtor: 'Noah Bennett',
      sellerLawyer: 'Beacon Law | 403-555-0190',
      buyerLawyer: 'West Ridge Legal | 403-555-0148',
      clientEmail: 'carter.nguyen@example.com',
      operatorNotes:
        'Live happy-path sample for the roundtable. Keep this one ready for the click-through demo.',
      sampleProfile: 'live',
    }),
  }),
});
